# renovate: datasource=docker packageName=alpine versioning=docker
ARG ALPINE_VERSION=3.22.2
FROM alpine:${ALPINE_VERSION}

# renovate: datasource=github-tags depName=helm/helm packageName=helm/helm
ARG HELM_VERSION=v3.13.0